### ISSUE TITLE
Is this a thing

### ISSUE THREAD

**Issue by DingusShingleton** [iscgar/tb-autohide-switcher#1]
Hello. I am searching for the smallest, lightest, and simplest possible method to toggle autohiding of my taskbar. This seems perfect; is it an active project? And if so, how do I use it?

Thanks

**Comment by iscgar** [comment]
As far as being a working program that does what its name suggests it does, it's very much a thing -- an old toy program that I wrote when I started developing in C# back in 2010 and decided to put on Github when I found it on my computer in 2013 and wanted to back it up somewhere.

It isn't an active project in the sense that there's no new development done, but that's only because there's no need to do anything since it's working as expected. I just pushed a new commit which only cleans up the code because it was embarrassing to look at it as it was.

The repo only contains the source code for the program. In order to use it you need to compile it using any version of Visual Studio. Then you can just put it anywhere you want and run it.

**Comment by DingusShingleton** [comment]
Awesome, thank you! I am stunned at how annoying and unreliable autohide still is in 2017... but here we are.

Managed somehow to install VS and build it. It's just what I have been searching for! Fantastic!
